services:
  yolo-api:
    build:
      context: ./be-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./be-fastapi:/app
    environment:
      - TZ=UTC
    restart: unless-stopped

  fastapi-densenet:
    build:
      context: ./be-fastapi-densenet
    ports:
      - "5005:5000"
    environment:
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - TZ=UTC
    volumes:
      - ./be-fastapi-densenet/models:/app/models
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: appsmith-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: appsmith
    restart: unless-stopped

  appsmith:
    image: appsmith/appsmith-ce
    container_name: appsmith
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./fe-appsmith:/app-config
      - appsmith-data:/appsmith-stacks/data
    environment:
      - APPSMITH_DATABASE_TYPE=mongodb
      - APPSMITH_DATABASE_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/appsmith
      - APPSMITH_IMPORT_APP=/app-config/PatientManagementApp.json
    depends_on:
      - mongo
    restart: unless-stopped


volumes:
  prometheus-data:
  grafana-data:
  appsmith-data:
  mongo-data:
