name: FastAPI CI/CD

on:
  push:
    branches: [main]
    paths:
      - "be-fastapi/**"
  pull_request:
    branches: [main]
    paths:
      - "be-fastapi/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mediscan-api ./be-fastapi

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mediscan-api

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mediscan-api
          docker run -d \
            -p 8000:8000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/mediscan-api

      - name: Trigger Deploy Hook (for Render)
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
